import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const username = cookies().get("username")?.value

  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-screen overflow-x-hidden flex flex-col`}>
        <Navbar username={username} />
        {children}
      </body>
    </html>
  );
}
